language: python
notifications:
  email: false
dist: xenial
sudo: false
python:
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install masonite_cli
  - pip install -r requirements.txt
script:
  - pytest tests --cov=codecov
after_success:
  - codecov
