language: python
notifications:
  email: false
dist: xenial
sudo: false
python:
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install masonite_cli
  - pip install -r requirements.txt
script:
  - python -m pytest --cov-report term --cov-report xml --cov=tests
after_success:
  - codecov
