language: python

before_script:
  - psql -c 'create database conduit;' -U postgres

python:
- '3.5'
- '3.6'

install:
- pip install pipenv --upgrade
- pipenv install
- travis_retry coverage run -m pytest && codecov
