language: python
notifications:
  email: false
before_script:
  - psql -c 'create database conduit;' -U postgres
dist: xenial
sudo: false
python:
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install pipenv --upgrade
  - pipenv install
script:
  - py.test tests --cov=codecov
after_success:
  - codecov
